/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_jesúsmeraz;

import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Jesús Meraz
 */
public class Lab5_JesúsMeraz extends javax.swing.JFrame {

    /**
     * Creates new form Lab5_JesúsMeraz
     */
    public Lab5_JesúsMeraz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup_modificar = new javax.swing.JPopupMenu();
        jmi_modificar = new javax.swing.JMenuItem();
        menu_popup = new javax.swing.JPopupMenu();
        opcion_edad = new javax.swing.JMenuItem();
        opcion_eliminar = new javax.swing.JMenuItem();
        opcion_modificar = new javax.swing.JMenuItem();
        opcion_Cuenta = new javax.swing.JMenuItem();
        popup_modificar1 = new javax.swing.JPopupMenu();
        jmi_modificar1 = new javax.swing.JMenuItem();
        popup_modificar2 = new javax.swing.JPopupMenu();
        cr = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        AE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        EE = new javax.swing.JSpinner();
        GeneroE = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_personas = new javax.swing.JList();
        CE = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        AM = new javax.swing.JTextField();
        NM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Salario = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        EE1 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        GeneroM = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_M = new javax.swing.JList();
        btnM = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Nclase = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        edificio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Seccion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        SINO = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jl_C = new javax.swing.JList();
        btnM1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        salon = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        facu = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        carreras = new javax.swing.JComboBox<>();
        costo = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jefe = new javax.swing.JTextField();
        btnM2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        JLcarreras = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_personas = new javax.swing.JTree();

        jmi_modificar.setText("modificar");
        jmi_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_modificarActionPerformed(evt);
            }
        });
        popup_modificar.add(jmi_modificar);

        opcion_edad.setText("ver edad");
        opcion_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion_edadActionPerformed(evt);
            }
        });
        menu_popup.add(opcion_edad);

        opcion_eliminar.setText("eliminar persona");
        opcion_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion_eliminarActionPerformed(evt);
            }
        });
        menu_popup.add(opcion_eliminar);

        opcion_modificar.setText("modificar nombre");
        opcion_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion_modificarActionPerformed(evt);
            }
        });
        menu_popup.add(opcion_modificar);

        opcion_Cuenta.setText("Ver numero de cuenta");
        opcion_Cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion_CuentaActionPerformed(evt);
            }
        });
        menu_popup.add(opcion_Cuenta);

        jmi_modificar1.setText("modificar");
        jmi_modificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_modificar1ActionPerformed(evt);
            }
        });
        popup_modificar1.add(jmi_modificar1);

        cr.setText("modificar");
        cr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crActionPerformed(evt);
            }
        });
        popup_modificar2.add(cr);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ingrese su nombre:");

        jLabel2.setText("Ingrese su apellido:");

        jLabel4.setText("Ingrese su edad:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Genero:");

        jLabel5.setText("Ingrese su carrera:");

        jButton1.setText("Agregar a la lista");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Agregar al arbol");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        EE.setValue(20);

        GeneroE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        jl_personas.setModel(new DefaultListModel());
        jl_personas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_personasMouseClicked(evt);
            }
        });
        jl_personas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jl_personasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jl_personas);

        CE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Finanzas", " Derecho", "Administración de Empresas", "Diseño Gráfico", "Mercadotecnia", "Sistemas Computacionales", "Industrial y de Sistemas", "Mecatrónica", "Biomédica", "Energía", "Medicina y Cirugía", "Odontología", "Nutrición y Terapia Física", "Ocupacional. ", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NE)
                    .addComponent(AE, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(GeneroE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EE, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(EE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(GeneroE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Estudiantes", jPanel1);

        jLabel6.setText("Ingrese su nombre:");

        jLabel8.setText("Ingrese su apellido:");

        jLabel9.setText("Ingrese su salario:");

        Salario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel10.setText("Ingrese su edad:");

        EE1.setValue(20);

        jLabel11.setText("Ingrese clases que imparte:");

        GeneroM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Genero:");

        jl_M.setModel(new DefaultListModel());
        jl_M.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_MMouseClicked(evt);
            }
        });
        jl_M.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jl_MKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jl_M);

        btnM.setText("Agregar a la lista");
        btnM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NM)
                    .addComponent(AM, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(Salario, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(GeneroM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EE1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2))
                .addGap(71, 71, 71))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(btnM, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(285, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(NM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(GeneroM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(EE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnM, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Maestros", jPanel2);

        jLabel13.setText("Ingrese Nombre de la clase: ");

        jLabel14.setText("Ingrese seccion:");

        jLabel15.setText("Ingrese edificio:");

        jLabel16.setText("Ingrese si dispone de aire acondicionado:");

        SINO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        jl_C.setModel(new DefaultListModel());
        jl_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_CMouseClicked(evt);
            }
        });
        jl_C.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jl_CKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(jl_C);

        btnM1.setText("Agregar a la lista");
        btnM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnM1MouseClicked(evt);
            }
        });

        jLabel17.setText("Ingrese el salon:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SINO, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel15)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(salon, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel14))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(edificio, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Nclase, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Seccion, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(btnM1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 223, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Nclase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Seccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(edificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(SINO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(salon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(btnM1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clases", jPanel3);

        jLabel3.setText("Ingrese Nombre de la carrera: ");

        facu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Licenciaturas", "Ingenierías", "Ciencias de la Salud" }));

        jLabel18.setText("Ingrese su facultad:");

        carreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Finanzas", " Derecho", "Administración de Empresas", "Diseño Gráfico", "Mercadotecnia", "Sistemas Computacionales", "Industrial y de Sistemas", "Mecatrónica", "Biomédica", "Energía", "Medicina y Cirugía", "Odontología", "Nutrición y Terapia Física", "Ocupacional. ", " " }));

        costo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel19.setText("Ingrese su costo mensual:");

        jLabel20.setText("Ingrese su jefe de carrera:");

        btnM2.setText("Agregar a la lista");
        btnM2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnM2MouseClicked(evt);
            }
        });

        JLcarreras.setModel(new DefaultListModel());
        JLcarreras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLcarrerasMouseClicked(evt);
            }
        });
        JLcarreras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JLcarrerasKeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(JLcarreras);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(137, 137, 137)
                        .addComponent(carreras, 0, 250, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(160, 160, 160)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(facu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(costo)
                            .addComponent(jefe))))
                .addGap(86, 86, 86))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(btnM2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(carreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(facu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnM2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Carreras", jPanel4);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Estudiantes");
        jt_personas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_personas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_personasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_personas);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Arbol", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Random random = new Random();
        int NumCuenta;
        NumCuenta = 10000000 + random.nextInt(99999999);
        DefaultListModel modelo
                = (DefaultListModel) jl_personas.getModel();
        modelo.addElement(new Estudiantes(NumCuenta,
                (String) CE.getSelectedItem(),
                NE.getText(),
                AE.getText(),
                (Integer) EE.getValue(),
                (String) GeneroE.getSelectedItem()
        )
        );
        jl_personas.setModel(modelo);
        NE.setText("");
        CE.setSelectedIndex(0);
        AE.setText("");
        EE.setValue(0);
        GeneroE.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jl_personasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_personasMouseClicked
        if (jl_personas.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                popup_modificar.show(evt.getComponent(),
                        evt.getX(), evt.getY());

            }
        }
    }//GEN-LAST:event_jl_personasMouseClicked

    private void jl_personasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jl_personasKeyPressed
        if (evt.getKeyCode() == evt.VK_DELETE) {
            if (jl_personas.getSelectedIndex() >= 0) {
                DefaultListModel modelo
                        = (DefaultListModel) jl_personas.getModel();
                modelo.remove(jl_personas.getSelectedIndex());
                jl_personas.setModel(modelo);
                JOptionPane.showMessageDialog(this,
                        "Eliminado exitosamente");

            }
        }
    }//GEN-LAST:event_jl_personasKeyPressed

    private void jt_personasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_personasMouseClicked
        if (evt.isMetaDown()) {
            //seleccionar un nodo con click derecho
            int row = jt_personas.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            jt_personas.setSelectionRow(row);
            Object v1
                    = jt_personas.getSelectionPath().
                            getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Estudiantes) {
                persona_seleccionada
                        = (Estudiantes) nodo_seleccionado.
                                getUserObject();
                menu_popup.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }

        }
    }//GEN-LAST:event_jt_personasMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if (jl_personas.getSelectedIndex() >= 0) {
            DefaultTreeModel modeloARBOL = (DefaultTreeModel) jt_personas.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            //obtener la persona a guardar
            DefaultListModel modeloLISTA = (DefaultListModel) jl_personas.getModel();
            int Numero_Cuenta;
            String Carrera;
            String Nombre;
            String Apellido;
            int Edad;
            String Genero;
            Numero_Cuenta = ((Estudiantes) modeloLISTA.get(jl_personas.getSelectedIndex())).getNumero_Cuenta();
            Carrera = ((Estudiantes) modeloLISTA.get(jl_personas.getSelectedIndex())).getCarrera();
            Nombre = ((Estudiantes) modeloLISTA.get(jl_personas.getSelectedIndex())).getNombre();
            Apellido = ((Estudiantes) modeloLISTA.get(jl_personas.getSelectedIndex())).getApellido();
            Edad = ((Estudiantes) modeloLISTA.get(jl_personas.getSelectedIndex())).getEdad();
            Genero = ((Estudiantes) modeloLISTA.get(jl_personas.getSelectedIndex())).getGenero();
            int centinela = -1;
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().
                        equals(Carrera)) {
                    DefaultMutableTreeNode p
                            = new DefaultMutableTreeNode(
                                    new Estudiantes(Numero_Cuenta, Carrera, Nombre, Apellido, Edad, Genero)
                            );
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                    centinela = 1;
                } //fin if
            } //fin for  

            if (centinela == -1) {
                DefaultMutableTreeNode n
                        = new DefaultMutableTreeNode(Carrera);
                DefaultMutableTreeNode p
                        = new DefaultMutableTreeNode(
                                new Estudiantes(Numero_Cuenta, Carrera, Nombre, Apellido, Edad, Genero)
                        );
                n.add(p);
                raiz.add(n);
            }  // fin if          
            modeloARBOL.reload();
            JOptionPane.showMessageDialog(this, "Se ha agregado al arbol");
        } else {
            JOptionPane.showMessageDialog(this,
                    "No hay persona seleccionada");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jmi_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_modificarActionPerformed
        // TODO add your handling code here:
        if (jl_personas.getSelectedIndex() >= 0) {
            DefaultListModel modeloLISTA = (DefaultListModel) jl_personas.getModel();
            ((Estudiantes) modeloLISTA.get(jl_personas.getSelectedIndex())).setNombre(JOptionPane.showInputDialog("Nombre"));
            ((Estudiantes) modeloLISTA.get(jl_personas.getSelectedIndex())).setApellido(JOptionPane.showInputDialog("Apellido"));
            ((Estudiantes) modeloLISTA.get(jl_personas.getSelectedIndex())).setEdad(Integer.parseInt(JOptionPane.showInputDialog("Edad")));
            ((Estudiantes) modeloLISTA.get(jl_personas.getSelectedIndex())).setCarrera(JOptionPane.showInputDialog("Carrera"));
            ((Estudiantes) modeloLISTA.get(jl_personas.getSelectedIndex())).setGenero(JOptionPane.showInputDialog("Genero"));
        }
    }//GEN-LAST:event_jmi_modificarActionPerformed

    private void opcion_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion_edadActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
                "TIENE UNA EDAD DE " + persona_seleccionada.
                        getEdad()
                + " AÑOS");
    }//GEN-LAST:event_opcion_edadActionPerformed

    private void opcion_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion_eliminarActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(
                this,
                "Seguro de Eliminar?",
                "Confirm",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.OK_OPTION) {
            DefaultTreeModel m
                    = (DefaultTreeModel) jt_personas.getModel();
            m.removeNodeFromParent(
                    nodo_seleccionado);
            m.reload();
        }
    }//GEN-LAST:event_opcion_eliminarActionPerformed

    private void opcion_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion_modificarActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) jt_personas.getModel();
        persona_seleccionada.setNombre(JOptionPane.showInputDialog("Nombre"));
        persona_seleccionada.setApellido(JOptionPane.showInputDialog("Apellido"));
        persona_seleccionada.setEdad(Integer.parseInt(JOptionPane.showInputDialog("Edad")));
        persona_seleccionada.setCarrera(JOptionPane.showInputDialog("Carrera"));
        persona_seleccionada.setGenero(JOptionPane.showInputDialog("Genero"));
        m.reload();
    }//GEN-LAST:event_opcion_modificarActionPerformed

    private void opcion_CuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion_CuentaActionPerformed
        JOptionPane.showMessageDialog(this, "Su numero de cuenta es: " + persona_seleccionada.getNumero_Cuenta());
    }//GEN-LAST:event_opcion_CuentaActionPerformed

    private void jl_MMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_MMouseClicked
        if (jl_M.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                popup_modificar1.show(evt.getComponent(),
                        evt.getX(), evt.getY());

            }
        }
    }//GEN-LAST:event_jl_MMouseClicked

    private void jl_MKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jl_MKeyPressed
        if (evt.getKeyCode() == evt.VK_DELETE) {
            if (jl_M.getSelectedIndex() >= 0) {
                DefaultListModel modelo
                        = (DefaultListModel) jl_M.getModel();
                modelo.remove(jl_M.getSelectedIndex());
                jl_M.setModel(modelo);
                JOptionPane.showMessageDialog(this,
                        "Eliminado exitosamente");

            }
        }
    }//GEN-LAST:event_jl_MKeyPressed

    private void btnMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMMouseClicked
        DefaultListModel modelo = (DefaultListModel) jl_M.getModel();
        modelo.addElement(new Maestros(Integer.parseInt(this.Salario.getText()),
                NM.getText(),
                AM.getText(),
                (Integer) EE1.getValue(),
                (String) GeneroM.getSelectedItem()
        )
        );
        jl_M.setModel(modelo);
        Salario.setText("");
        NM.setText("");
        AM.setText("");
        EE1.setValue(0);
        GeneroM.setSelectedIndex(0);
    }//GEN-LAST:event_btnMMouseClicked

    private void jl_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_CMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jl_CMouseClicked

    private void jl_CKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jl_CKeyPressed
        if (evt.getKeyCode() == evt.VK_DELETE) {
            if (jl_C.getSelectedIndex() >= 0) {
                DefaultListModel modelo
                        = (DefaultListModel) jl_C.getModel();
                modelo.remove(jl_C.getSelectedIndex());
                jl_C.setModel(modelo);
                JOptionPane.showMessageDialog(this,
                        "Eliminado exitosamente");

            }
        }
    }//GEN-LAST:event_jl_CKeyPressed

    private void btnM1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnM1MouseClicked
        DefaultListModel modelo = (DefaultListModel) jl_C.getModel();
        modelo.addElement(new Clases(Nclase.getText(),
                Seccion.getText(),
                edificio.getText(),
                salon.getText(),
                (String) SINO.getSelectedItem()
        )
        );
        jl_C.setModel(modelo);
        Nclase.setText("");
        Seccion.setText("");
        edificio.setText("");
        salon.setText("");
        SINO.setSelectedIndex(0);
    }//GEN-LAST:event_btnM1MouseClicked

    private void jmi_modificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_modificar1ActionPerformed
        if (jl_M.getSelectedIndex() >= 0) {
            DefaultListModel modeloLISTA = (DefaultListModel) jl_M.getModel();
            ((Maestros) modeloLISTA.get(jl_M.getSelectedIndex())).setNombre(JOptionPane.showInputDialog("Nombre"));
            ((Maestros) modeloLISTA.get(jl_M.getSelectedIndex())).setApellido(JOptionPane.showInputDialog("Apellido"));
            ((Maestros) modeloLISTA.get(jl_M.getSelectedIndex())).setEdad(Integer.parseInt(JOptionPane.showInputDialog("Año")));
            ((Maestros) modeloLISTA.get(jl_M.getSelectedIndex())).setGenero(JOptionPane.showInputDialog("Genero"));
            ((Maestros) modeloLISTA.get(jl_M.getSelectedIndex())).setSalario(Integer.parseInt(JOptionPane.showInputDialog("Salario")));
        }
    }//GEN-LAST:event_jmi_modificar1ActionPerformed

    private void btnM2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnM2MouseClicked
        DefaultListModel modelo = (DefaultListModel) JLcarreras.getModel();
        modelo.addElement(new Carrera((String) carreras.getSelectedItem(),
                (String) facu.getSelectedItem(),
                Integer.parseInt(this.costo.getText()),
                jefe.getText()
        )
        );
        jl_C.setModel(modelo);
        Nclase.setText("");
        Seccion.setText("");
        edificio.setText("");
        salon.setText("");
        SINO.setSelectedIndex(0);
    }//GEN-LAST:event_btnM2MouseClicked

    private void JLcarrerasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLcarrerasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_JLcarrerasMouseClicked

    private void JLcarrerasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JLcarrerasKeyPressed
        if (evt.getKeyCode() == evt.VK_DELETE) {
            if (JLcarreras.getSelectedIndex() >= 0) {
                DefaultListModel modelo
                        = (DefaultListModel) JLcarreras.getModel();
                modelo.remove(JLcarreras.getSelectedIndex());
                JLcarreras.setModel(modelo);
                JOptionPane.showMessageDialog(this,
                        "Eliminado exitosamente");

            }
        }
    }//GEN-LAST:event_JLcarrerasKeyPressed

    private void crActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crActionPerformed
        if (JLcarreras.getSelectedIndex() >= 0) {
            DefaultListModel modeloLISTA = (DefaultListModel) JLcarreras.getModel();
            ((Carrera) modeloLISTA.get(JLcarreras.getSelectedIndex())).setJefe_Carrera(JOptionPane.showInputDialog("Jefe"));
            ((Carrera) modeloLISTA.get(JLcarreras.getSelectedIndex())).setCosto_Mensual(Integer.parseInt(JOptionPane.showInputDialog("Costo")));
        }
    }//GEN-LAST:event_crActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab5_JesúsMeraz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab5_JesúsMeraz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab5_JesúsMeraz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab5_JesúsMeraz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab5_JesúsMeraz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AE;
    private javax.swing.JTextField AM;
    private javax.swing.JComboBox<String> CE;
    private javax.swing.JSpinner EE;
    private javax.swing.JSpinner EE1;
    private javax.swing.JComboBox<String> GeneroE;
    private javax.swing.JComboBox<String> GeneroM;
    private javax.swing.JList JLcarreras;
    private javax.swing.JTextField NE;
    private javax.swing.JTextField NM;
    private javax.swing.JTextField Nclase;
    private javax.swing.JComboBox<String> SINO;
    private javax.swing.JFormattedTextField Salario;
    private javax.swing.JTextField Seccion;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnM1;
    private javax.swing.JButton btnM2;
    private javax.swing.JComboBox<String> carreras;
    private javax.swing.JFormattedTextField costo;
    private javax.swing.JMenuItem cr;
    private javax.swing.JTextField edificio;
    private javax.swing.JComboBox<String> facu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jefe;
    private javax.swing.JList jl_C;
    private javax.swing.JList jl_M;
    private javax.swing.JList jl_personas;
    private javax.swing.JMenuItem jmi_modificar;
    private javax.swing.JMenuItem jmi_modificar1;
    private javax.swing.JTree jt_personas;
    private javax.swing.JPopupMenu menu_popup;
    private javax.swing.JMenuItem opcion_Cuenta;
    private javax.swing.JMenuItem opcion_edad;
    private javax.swing.JMenuItem opcion_eliminar;
    private javax.swing.JMenuItem opcion_modificar;
    private javax.swing.JPopupMenu popup_modificar;
    private javax.swing.JPopupMenu popup_modificar1;
    private javax.swing.JPopupMenu popup_modificar2;
    private javax.swing.JTextField salon;
    // End of variables declaration//GEN-END:variables
DefaultMutableTreeNode nodo_seleccionado;
    Estudiantes persona_seleccionada;

}
